name: First Workflow
on: workflow_dispatch
  push:
    branches-ignore:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done Dude bye!"  