name: First Workflow
on:
  push: 
    branches: [ main/master ]
  pull_request:
    branches: [ main/master ]
  workflow_dispatch:
    branches: [main/master]        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"